baseURL = "https://vrk.sh"
languageCode = "en-us"
title = "vrksh"

# Clean URLs: /docs/tok/ not /docs/tok.html
uglyURLs = false

[params]
  description = "The missing coreutils for the agent era. One binary. No dependencies."
  tagline = "The missing coreutils for the agent era."
  version = "0.1.0"
  github = "https://github.com/vrksh/vrksh"

[[module.mounts]]
  source = "content"
  target = "content"
[[module.mounts]]
  source = "static"
  target = "static"
[[module.mounts]]
  source = "layouts"
  target = "layouts"
[[module.mounts]]
  source = "data"
  target = "data"
[[module.mounts]]
  source = "../schema"
  target = "data/schema"

[markup]
  [markup.highlight]
    codeFences = false
    noClasses = false
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
