package tok

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"strings"
	"testing"
)

// hundred is a string of exactly 100 cl100k_base tokens.
// Generated by the throwaway generator in PLAN.md §build-order step 3d.
// Verified: len(enc.Encode(hundred, nil, nil)) == 100. Do not edit manually.
const hundred = "the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog "

// runTok replaces os.Stdin/Stdout/Stderr and os.Args, calls Run(), and returns
// captured stdout, stderr, and the exit code. t.Cleanup restores all globals.
// Do not call t.Parallel() on tests using this helper — they share global state.
func runTok(t *testing.T, args []string, stdinContent string) (stdout, stderr string, code int) {
	t.Helper()

	origStdin := os.Stdin
	origStdout := os.Stdout
	origStderr := os.Stderr
	origArgs := os.Args

	t.Cleanup(func() {
		os.Stdin = origStdin
		os.Stdout = origStdout
		os.Stderr = origStderr
		os.Args = origArgs
	})

	// stdin: always a pipe so Run() sees a non-TTY stdin and doesn't block.
	stdinR, stdinW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stdin pipe: %v", err)
	}
	if _, err := io.WriteString(stdinW, stdinContent); err != nil {
		t.Fatalf("write stdin: %v", err)
	}
	if err := stdinW.Close(); err != nil {
		t.Fatalf("close stdin write end: %v", err)
	}
	os.Stdin = stdinR

	stdoutR, stdoutW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stdout pipe: %v", err)
	}
	os.Stdout = stdoutW

	stderrR, stderrW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stderr pipe: %v", err)
	}
	os.Stderr = stderrW

	os.Args = append([]string{"tok"}, args...)

	code = Run()

	// Close write ends before reading so io.Copy sees EOF.
	_ = stdoutW.Close()
	_ = stderrW.Close()

	var outBuf, errBuf bytes.Buffer
	if _, err := io.Copy(&outBuf, stdoutR); err != nil {
		t.Fatalf("read stdout: %v", err)
	}
	if _, err := io.Copy(&errBuf, stderrR); err != nil {
		t.Fatalf("read stderr: %v", err)
	}
	_ = stdoutR.Close()
	_ = stderrR.Close()

	return outBuf.String(), errBuf.String(), code
}

// --- Hardcoded counts (cl100k_base, not implementation choices) ---

func TestHelloWorldCount(t *testing.T) {
	// "hello world" → 2 tokens via cl100k_base.
	stdout, _, code := runTok(t, nil, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestHelloWorldCountArg(t *testing.T) {
	// Positional arg form must produce the same result as stdin form.
	stdout, _, code := runTok(t, []string{"hello world"}, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestEmptyStdin(t *testing.T) {
	// Empty pipe (zero bytes) is not an error — it is 0 tokens.
	stdout, _, code := runTok(t, nil, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "0\n" {
		t.Errorf("stdout = %q, want %q", stdout, "0\n")
	}
}

func TestDevNull(t *testing.T) {
	// A pipe carrying zero bytes is equivalent to /dev/null — 0 tokens, exit 0.
	// (TTY detection uses os.ModeCharDevice; a pipe never triggers it.)
	stdout, _, code := runTok(t, nil, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "0\n" {
		t.Errorf("stdout = %q, want %q", stdout, "0\n")
	}
}

func TestHelloCommaWorld(t *testing.T) {
	// "Hello, world!" → 4 tokens via cl100k_base.
	stdout, _, code := runTok(t, nil, "Hello, world!")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "4\n" {
		t.Errorf("stdout = %q, want %q", stdout, "4\n")
	}
}

// --- --json ---

func TestJsonOutput(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--json"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(strings.TrimSpace(stdout)), &obj); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\ngot: %q", err, stdout)
	}
	// tokens field must be 2.
	tokensRaw, ok := obj["tokens"]
	if !ok {
		t.Fatal("JSON missing key \"tokens\"")
	}
	// json.Unmarshal decodes numbers as float64 in map[string]any.
	if int(tokensRaw.(float64)) != 2 {
		t.Errorf("tokens = %v, want 2", tokensRaw)
	}
	// model field must be present and non-empty.
	model, ok := obj["model"]
	if !ok {
		t.Fatal("JSON missing key \"model\"")
	}
	if model == "" {
		t.Error("model field is empty")
	}
}

// --- --check ---

func TestTokCheckWithinLimitNoNewline(t *testing.T) {
	// "hello world" (no trailing \n) passes through byte-for-byte, exit 0.
	stdout, stderr, code := runTok(t, []string{"--check", "8000"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "hello world" {
		t.Errorf("stdout = %q, want %q", stdout, "hello world")
	}
	if stderr != "" {
		t.Errorf("stderr = %q, want empty (silent success)", stderr)
	}
}

func TestTokCheckWithinLimitNewline(t *testing.T) {
	// "hello world\n" (with trailing \n) passes through byte-for-byte, exit 0.
	stdout, stderr, code := runTok(t, []string{"--check", "8000"}, "hello world\n")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "hello world\n" {
		t.Errorf("stdout = %q, want %q", stdout, "hello world\n")
	}
	if stderr != "" {
		t.Errorf("stderr = %q, want empty (silent success)", stderr)
	}
}

func TestTokCheckSilentSuccess(t *testing.T) {
	// --check within limit: stderr must be empty (no informational message).
	_, stderr, code := runTok(t, []string{"--check", "8000"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stderr != "" {
		t.Errorf("stderr = %q, want empty", stderr)
	}
}

func TestTokCheckOverLimit(t *testing.T) {
	// "hello world" = 2 tokens; --check 1 → over limit, exit 1, stdout empty.
	stdout, _, code := runTok(t, []string{"--check", "1"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1 (over limit)", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty on over-limit, got %q", stdout)
	}
}

func TestTokCheckQuiet(t *testing.T) {
	// --check within limit + --quiet: stderr empty, input passes through.
	stdout, stderr, code := runTok(t, []string{"--check", "8000", "--quiet"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "hello world" {
		t.Errorf("stdout = %q, want %q", stdout, "hello world")
	}
	if stderr != "" {
		t.Errorf("--quiet: stderr = %q, want empty", stderr)
	}
}

func TestTokCheckQuietOverLimit(t *testing.T) {
	// --check over limit + --quiet: stderr empty, stdout empty, exit 1.
	stdout, stderr, code := runTok(t, []string{"--check", "1", "--quiet"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty, got %q", stdout)
	}
	if stderr != "" {
		t.Errorf("--quiet: stderr = %q, want empty", stderr)
	}
}

func TestTokCheckJSONOverLimit(t *testing.T) {
	// --check over limit + --json: JSON error on stdout, stderr empty, exit 1.
	stdout, stderr, code := runTok(t, []string{"--check", "1", "--json"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}
	if stderr != "" {
		t.Errorf("--json: stderr must be empty, got %q", stderr)
	}
	if stdout == "" {
		t.Fatal("--json: stdout must contain JSON error, got empty")
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(strings.TrimSpace(stdout)), &obj); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\ngot: %q", err, stdout)
	}
	if _, ok := obj["error"]; !ok {
		t.Error("JSON missing key \"error\"")
	}
	if _, ok := obj["tokens"]; !ok {
		t.Error("JSON missing key \"tokens\"")
	}
	if _, ok := obj["limit"]; !ok {
		t.Error("JSON missing key \"limit\"")
	}
	if c, _ := obj["code"].(float64); int(c) != 1 {
		t.Errorf("code = %v, want 1", obj["code"])
	}
}

func TestTokCheckJSONWithinLimit(t *testing.T) {
	// --check within limit + --json: raw passthrough (not JSON), exit 0.
	stdout, stderr, code := runTok(t, []string{"--check", "8000", "--json"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "hello world" {
		t.Errorf("stdout = %q, want %q (raw passthrough, not JSON)", stdout, "hello world")
	}
	if stderr != "" {
		t.Errorf("stderr = %q, want empty", stderr)
	}
}

func TestTokCheckByteForByte(t *testing.T) {
	// Exact bytes preserved: whitespace, no trailing newline added.
	input := `{"a":1,  "b":2}`
	stdout, _, code := runTok(t, []string{"--check", "8000"}, input)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != input {
		t.Errorf("stdout = %q, want %q (byte-for-byte)", stdout, input)
	}
}

func TestTokCheckDoubleNewline(t *testing.T) {
	// Input ending in \n\n: raw bytes preserved in stdout.
	// Token count is on stripped string (one trailing \n removed).
	input := "hello world\n\n"
	stdout, _, code := runTok(t, []string{"--check", "8000"}, input)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != input {
		t.Errorf("stdout = %q, want %q", stdout, input)
	}
}

func TestTokCheckNoValue(t *testing.T) {
	// --check without an integer argument: exit 2 with clear message.
	_, stderr, code := runTok(t, []string{"--check"}, "hello world")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2", code)
	}
	if !strings.Contains(stderr, "requires a token limit") {
		t.Errorf("stderr = %q, want it to contain %q", stderr, "requires a token limit")
	}
}

func TestTokCheckZero(t *testing.T) {
	// --check 0 with non-empty input: any positive count > 0, exit 1.
	stdout, _, code := runTok(t, []string{"--check", "0"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty, got %q", stdout)
	}
}

func TestTokCheckZeroEmpty(t *testing.T) {
	// --check 0 with empty input: 0 tokens <= 0, exit 0.
	stdout, _, code := runTok(t, []string{"--check", "0"}, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "" {
		t.Errorf("stdout = %q, want empty", stdout)
	}
}

func TestTokCheckPositionalArg(t *testing.T) {
	// Positional arg + --check: passes through joined args, no trailing newline.
	stdout, _, code := runTok(t, []string{"--check", "8000", "hello world"}, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "hello world" {
		t.Errorf("stdout = %q, want %q", stdout, "hello world")
	}
}

func TestJSONErrorToStdout(t *testing.T) {
	// Canonical contract test: --json routes --check errors to stdout as JSON.
	stdout, stderr, code := runTok(t, []string{"--check", "1", "--json"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}
	if stderr != "" {
		t.Errorf("stderr must be empty when --json active, got %q", stderr)
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(strings.TrimSpace(stdout)), &obj); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\ngot: %q", err, stdout)
	}
	if _, ok := obj["error"]; !ok {
		t.Error("JSON missing key \"error\"")
	}
}

// --- --model ---

func TestModelFlag(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--model", "cl100k_base"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestJsonWithModelFlag(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--model", "cl100k_base", "--json"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(strings.TrimSpace(stdout)), &obj); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\ngot: %q", err, stdout)
	}
	if model, _ := obj["model"].(string); model != "cl100k_base" {
		t.Errorf("model = %q, want %q", model, "cl100k_base")
	}
}

// --- no input (empty pipe — not TTY) ---

func TestNoInputEmptyPipe(t *testing.T) {
	// Empty pipe is not a usage error — it is 0 tokens.
	// TTY detection (exit 2) fires only when stdin is a character device;
	// in tests stdin is always a pipe, so this always takes the 0-token path.
	stdout, _, code := runTok(t, nil, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0 (empty pipe = 0 tokens)", code)
	}
	if stdout != "0\n" {
		t.Errorf("stdout = %q, want %q", stdout, "0\n")
	}
}

// --- error cases ---

func TestUnknownFlag(t *testing.T) {
	stdout, stderr, code := runTok(t, []string{"--unknown-flag"}, "")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2 (usage error)", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty on usage error, got %q", stdout)
	}
	if stderr == "" {
		t.Error("stderr must contain usage text, got empty")
	}
}

func TestHelp(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--help"}, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if !strings.Contains(stdout, "tok") {
		t.Errorf("stdout = %q, want it to contain %q", stdout, "tok")
	}
}

// --- 100-token fixture ---

func Test100TokenString(t *testing.T) {
	if hundred == "" {
		t.Skip("hundred const not yet generated — fill in after go get github.com/pkoukk/tiktoken-go")
	}
	stdout, _, code := runTok(t, nil, hundred)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "100\n" {
		t.Errorf("stdout = %q, want %q", stdout, "100\n")
	}
}

// --- --quiet flag tests ---

// TestQuietDoesNotAffectStdout verifies that --quiet does not suppress stdout
// on success.
func TestQuietDoesNotAffectStdout(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--quiet"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

// --- property test ---

func TestPropertyExitCodesOnly(t *testing.T) {
	// Any string input must produce an exit code in {0, 1, 2} — never anything else.
	inputs := []string{
		"hello world",
		"Hello, world!",
		"",
		strings.Repeat("a", 10000),
		"unicode: 日本語テスト",
		"\x00\x01\x02",
	}
	for _, input := range inputs {
		_, _, code := runTok(t, nil, input)
		if code != 0 && code != 1 && code != 2 {
			t.Errorf("input %q: exit code = %d, want 0, 1, or 2", input, code)
		}
	}
}

// --- fuzz ---

func FuzzTok(f *testing.F) {
	f.Add("hello world")
	f.Add("Hello, world!")
	f.Add("")
	f.Add(strings.Repeat("the quick brown fox ", 500))
	f.Add("unicode: 日本語テスト 한국어 中文")

	f.Fuzz(func(t *testing.T, input string) {
		_, _, code := runTok(t, nil, input)
		if code != 0 && code != 1 && code != 2 {
			t.Errorf("exit code = %d, want 0, 1, or 2", code)
		}
	})
}
