package tok

import (
	"bytes"
	"encoding/json"
	"io"
	"os"
	"strings"
	"testing"
)

// hundred is a string of exactly 100 cl100k_base tokens.
// Generated by the throwaway generator in PLAN.md §build-order step 3d.
// Verified: len(enc.Encode(hundred, nil, nil)) == 100. Do not edit manually.
const hundred = "the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog in some park on sunny day the quick brown fox jumps over a lazy dog "

// runTok replaces os.Stdin/Stdout/Stderr and os.Args, calls Run(), and returns
// captured stdout, stderr, and the exit code. t.Cleanup restores all globals.
// Do not call t.Parallel() on tests using this helper — they share global state.
func runTok(t *testing.T, args []string, stdinContent string) (stdout, stderr string, code int) {
	t.Helper()

	origStdin := os.Stdin
	origStdout := os.Stdout
	origStderr := os.Stderr
	origArgs := os.Args

	t.Cleanup(func() {
		os.Stdin = origStdin
		os.Stdout = origStdout
		os.Stderr = origStderr
		os.Args = origArgs
	})

	// stdin: always a pipe so Run() sees a non-TTY stdin and doesn't block.
	stdinR, stdinW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stdin pipe: %v", err)
	}
	if _, err := io.WriteString(stdinW, stdinContent); err != nil {
		t.Fatalf("write stdin: %v", err)
	}
	if err := stdinW.Close(); err != nil {
		t.Fatalf("close stdin write end: %v", err)
	}
	os.Stdin = stdinR

	stdoutR, stdoutW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stdout pipe: %v", err)
	}
	os.Stdout = stdoutW

	stderrR, stderrW, err := os.Pipe()
	if err != nil {
		t.Fatalf("stderr pipe: %v", err)
	}
	os.Stderr = stderrW

	os.Args = append([]string{"tok"}, args...)

	code = Run()

	// Close write ends before reading so io.Copy sees EOF.
	_ = stdoutW.Close()
	_ = stderrW.Close()

	var outBuf, errBuf bytes.Buffer
	if _, err := io.Copy(&outBuf, stdoutR); err != nil {
		t.Fatalf("read stdout: %v", err)
	}
	if _, err := io.Copy(&errBuf, stderrR); err != nil {
		t.Fatalf("read stderr: %v", err)
	}
	_ = stdoutR.Close()
	_ = stderrR.Close()

	return outBuf.String(), errBuf.String(), code
}

// --- Hardcoded counts (cl100k_base, not implementation choices) ---

func TestHelloWorldCount(t *testing.T) {
	// "hello world" → 2 tokens via cl100k_base.
	stdout, _, code := runTok(t, nil, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestHelloWorldCountArg(t *testing.T) {
	// Positional arg form must produce the same result as stdin form.
	stdout, _, code := runTok(t, []string{"hello world"}, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestEmptyStdin(t *testing.T) {
	// Empty pipe (zero bytes) is not an error — it is 0 tokens.
	stdout, _, code := runTok(t, nil, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "0\n" {
		t.Errorf("stdout = %q, want %q", stdout, "0\n")
	}
}

func TestDevNull(t *testing.T) {
	// A pipe carrying zero bytes is equivalent to /dev/null — 0 tokens, exit 0.
	// (TTY detection uses os.ModeCharDevice; a pipe never triggers it.)
	stdout, _, code := runTok(t, nil, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "0\n" {
		t.Errorf("stdout = %q, want %q", stdout, "0\n")
	}
}

func TestHelloCommaWorld(t *testing.T) {
	// "Hello, world!" → 4 tokens via cl100k_base.
	stdout, _, code := runTok(t, nil, "Hello, world!")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "4\n" {
		t.Errorf("stdout = %q, want %q", stdout, "4\n")
	}
}

// --- --json ---

func TestJsonOutput(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--json"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(strings.TrimSpace(stdout)), &obj); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\ngot: %q", err, stdout)
	}
	// tokens field must be 2.
	tokensRaw, ok := obj["tokens"]
	if !ok {
		t.Fatal("JSON missing key \"tokens\"")
	}
	// json.Unmarshal decodes numbers as float64 in map[string]any.
	if int(tokensRaw.(float64)) != 2 {
		t.Errorf("tokens = %v, want 2", tokensRaw)
	}
	// model field must be present and non-empty.
	model, ok := obj["model"]
	if !ok {
		t.Fatal("JSON missing key \"model\"")
	}
	if model == "" {
		t.Error("model field is empty")
	}
}

// --- --budget ---

func TestBudgetWithin(t *testing.T) {
	// "hello world" = 2 tokens; budget 5 → within budget, print count, exit 0.
	stdout, _, code := runTok(t, []string{"--budget", "5"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0 (within budget)", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestBudgetExceeded(t *testing.T) {
	// "hello world" = 2 tokens; budget 1 → over budget, exit 1, stdout empty.
	stdout, stderr, code := runTok(t, []string{"--budget", "1"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1 (over budget)", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty on budget failure, got %q", stdout)
	}
	if !strings.Contains(stderr, "2 tokens exceeds budget of 1") {
		t.Errorf("stderr = %q, want it to contain %q", stderr, "2 tokens exceeds budget of 1")
	}
}

func TestBudgetExceededWithFail(t *testing.T) {
	// --fail is redundant on tok (--budget is always a hard guard), but must
	// produce the same result as --budget alone.
	stdout, stderr, code := runTok(t, []string{"--budget", "1", "--fail"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1 (--budget 1 --fail)", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty on budget failure, got %q", stdout)
	}
	if !strings.Contains(stderr, "2 tokens exceeds budget of 1") {
		t.Errorf("stderr = %q, want it to contain %q", stderr, "2 tokens exceeds budget of 1")
	}
}

func TestBudgetPipelineOutputEmpty(t *testing.T) {
	// When budget is exceeded the tool exits 1 with nothing on stdout.
	// This simulates: echo 'hello world' | vrk tok --budget 1 --fail | wc -c → 0
	stdout, _, code := runTok(t, []string{"--budget", "1", "--fail"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}
	if len(stdout) != 0 {
		t.Errorf("stdout length = %d, want 0 (nothing must pass through on exit 1)", len(stdout))
	}
}

func TestBudgetExceededWithJSON(t *testing.T) {
	// --json must NOT change the error format when budget is exceeded.
	// Errors always go to stderr as plain text regardless of output flags.
	stdout, stderr, code := runTok(t, []string{"--budget", "1", "--json"}, "hello world")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty on budget failure, got %q", stdout)
	}
	// stderr must be plain text, not JSON.
	if strings.HasPrefix(strings.TrimSpace(stderr), "{") {
		t.Errorf("stderr looks like JSON — errors must be plain text: %q", stderr)
	}
	if !strings.Contains(stderr, "2 tokens exceeds budget of 1") {
		t.Errorf("stderr = %q, want it to contain %q", stderr, "2 tokens exceeds budget of 1")
	}
}

// --- --model ---

func TestModelFlag(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--model", "cl100k_base"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "2\n" {
		t.Errorf("stdout = %q, want %q", stdout, "2\n")
	}
}

func TestJsonWithModelFlag(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--model", "cl100k_base", "--json"}, "hello world")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(strings.TrimSpace(stdout)), &obj); err != nil {
		t.Fatalf("stdout is not valid JSON: %v\ngot: %q", err, stdout)
	}
	if model, _ := obj["model"].(string); model != "cl100k_base" {
		t.Errorf("model = %q, want %q", model, "cl100k_base")
	}
}

// --- no input (empty pipe — not TTY) ---

func TestNoInputEmptyPipe(t *testing.T) {
	// Empty pipe is not a usage error — it is 0 tokens.
	// TTY detection (exit 2) fires only when stdin is a character device;
	// in tests stdin is always a pipe, so this always takes the 0-token path.
	stdout, _, code := runTok(t, nil, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0 (empty pipe = 0 tokens)", code)
	}
	if stdout != "0\n" {
		t.Errorf("stdout = %q, want %q", stdout, "0\n")
	}
}

// --- error cases ---

func TestUnknownFlag(t *testing.T) {
	stdout, stderr, code := runTok(t, []string{"--unknown-flag"}, "")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2 (usage error)", code)
	}
	if stdout != "" {
		t.Errorf("stdout must be empty on usage error, got %q", stdout)
	}
	if stderr == "" {
		t.Error("stderr must contain usage text, got empty")
	}
}

func TestHelp(t *testing.T) {
	stdout, _, code := runTok(t, []string{"--help"}, "")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if !strings.Contains(stdout, "tok") {
		t.Errorf("stdout = %q, want it to contain %q", stdout, "tok")
	}
}

// --- 100-token fixture ---

func Test100TokenString(t *testing.T) {
	if hundred == "" {
		t.Skip("hundred const not yet generated — fill in after go get github.com/pkoukk/tiktoken-go")
	}
	stdout, _, code := runTok(t, nil, hundred)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}
	if stdout != "100\n" {
		t.Errorf("stdout = %q, want %q", stdout, "100\n")
	}
}

// --- property test ---

func TestPropertyExitCodesOnly(t *testing.T) {
	// Any string input must produce an exit code in {0, 1, 2} — never anything else.
	inputs := []string{
		"hello world",
		"Hello, world!",
		"",
		strings.Repeat("a", 10000),
		"unicode: 日本語テスト",
		"\x00\x01\x02",
	}
	for _, input := range inputs {
		_, _, code := runTok(t, nil, input)
		if code != 0 && code != 1 && code != 2 {
			t.Errorf("input %q: exit code = %d, want 0, 1, or 2", input, code)
		}
	}
}

// --- fuzz ---

func FuzzTok(f *testing.F) {
	f.Add("hello world")
	f.Add("Hello, world!")
	f.Add("")
	f.Add(strings.Repeat("the quick brown fox ", 500))
	f.Add("unicode: 日本語テスト 한국어 中文")

	f.Fuzz(func(t *testing.T, input string) {
		_, _, code := runTok(t, nil, input)
		if code != 0 && code != 1 && code != 2 {
			t.Errorf("exit code = %d, want 0, 1, or 2", code)
		}
	})
}
